---
title: 手写Promise
categories: [学习笔记]
comments: true
---

## 实现一个简易版 Promise

```
const PENDING = 'pending'
const RESOLVED = 'resolved'
const REJECTED = 'rejected'

function Promise(fn) {
  const that = this
  this.state = PENDING
  this.value = null
  this.resolvedCallbacks = []
  this.rejectedCallbacks = []


  function resolve(value) {
    if(that.state === PENDING) {
      that.state = RESOLVED
      that.value = value
      that.resolvedCallbacks.map(cb => cb(that.value))
    }
  }
  function reject(value) {
    if(that.state === PENDING) {
      that.state = REJECTED
      that.value = value
      that.rejectedCallbacks.map(cb => cb(that.value))
    }
  }

  try {
    fn(resolve, reject)
  } catch (e) {
    reject(e)
  }
}

Promise.prototype.then = function(onFulfilled, onRejected){
  const that = this
  onFulfilled = typeof === 'function' ? onFulfilled : v => v
  onRejected = typeof === 'function'
   ? onRejected
   : r => {
      throw r
     }
  if(that.state === PENDING) {
    that.resolvedCallbacks.push(onFulfilled)
    that.rejectedCallbacks.push(onRejected)
  }

  if(that.state === RESOLVED) {
    onFulfilled(that.value)
  }

  if(that.state === REJECTED) {
    onRejected(that.value)
  }
 }
```

## 实现一个符合 Promise/A+规范的 Promise

```
const PENDING = 'pending'
const RESOLVED = 'resolved'
const REJECTED = 'rejected'

function Promise(fn) {
  const that = this
  this.state = PENDING
  this.value = null
  this.resolvedCallbacks = []
  this.rejectedCallbacks = []


  function resolve(value) {
    if(value instanceof Promise) {
      return value.then(resolve, reject)
    }
    setTimeout(() => {
      if(that.state === PENDING) {
        that.state = RESOLVED
        that.value = value
        that.resolvedCallbacks.map(cb => cb(that.value))
      }
    }, 0)
  }
  function reject(value) {
    setTimeout(() => {
      if(that.state === PENDING) {
        that.state = REJECTED
        that.value = value
        that.rejectedCallbacks.map(cb => cb(that.value))
      }
    }, 0)
  }

  try {
    fn(resolve, reject)
  } catch (e) {
    reject(e)
  }

  function resolutionProcedure(promise2, x, resolve, reject) {
    if(promise2 === x) {
      return reject(new TypeError('error'))
    }
    if( x instanceof Promise) {
      x.then(function(value) {
        resolutionProcedure(promise2, value, resolve, reject)
      }, reject)
    }
  }
}

Promise.prototype.then = function(onFulfilled, onRejected){
  const that = this
  if(that.state === PENDING) {
    return (promise2 = new Promise(resolve, reject) => {
      that.resolvedCallbacks.push(() => {
        try {
          const x = onFulfilled(that.value)
          resolutionProcedure(promise2, x, resolve, reject)
        } catch (r) {
          reject(r)
        }
      })
      that.rejectedCallbacks.push(() => {
        try {
          const x = onRejected(that.value)
          resolutionProcedure(promise2, x, resolve, reject)
        }
      })
    })
  }
  onFulfilled = typeof === 'function' ? onFulfilled : v => v
  onRejected = typeof === 'function'
   ? onRejected
   : r => {
      throw r
     }

  if(that.state === RESOLVED) {
    onFulfilled(that.value)
    return(promise2 = new Promise(resolve, reject) => {
      setTimeout(() => {
        try {
          const x = onFulfilled(that.value)
          resolutionProcedure(promise2, x, resolve, reject)
        } catch(reason) {
          reject(reason)
        }
      })
    })
  }

  if(that.state === REJECTED) {
    onRejected(that.value)
  }
 }
```

## promise 数组串行执行

一组接口需要串行执行，第一种方法，使用 await

```
const requestArray = [() => api.request1(), () => api.request2(), () => api.request3()];
for( let requestItem of requestArray) {
  await requestItem;
}
```

如果使用 promise 的写法，那么你可以使用 then 函数来串联多个 promise，从而实现串行执行。

```
const requestArray = [() => api.request1(), () => api.request2(), () => api.request3()];
const finallyPromise = requestArray.reduce(
  (currentPromise, nextRequest) => currentPromise.then(() => nextRequest()),
  Promise.resolve() // 创建一个初始promise
)
```

## 同时调用 resolve 和 reject 会怎样

promise 分别有 pending/fulfilled/rejected 三种状态，下面例子最终是什么状态？

```
const promise = new Promise((resolve, reject) => {
  resolve();
  reject();
})
```

答案是 fulfilled 状态，因为 promise 一旦从 pending 状态转到另一种状态，就不可再更改，因此例子中先被转到了 fulfilled 状态，在调用 reject 也不会再更改状态。

## then/catch/finally 返回值

以上三个函数都会返回一个新的 promise 包装对象，被包装的值为被执行的回调函数的返回值，回调函数抛出错误则会包装一个 rejected 状态的 promise。

```
// then
Promise.resolve().then(() => 1); // 返回值为 new Promise(resolve => resolve(1))
Promise.resolve().then(() => Promise.resolve(2)); // 返回值为 new Promise(resolve => resolve(Promise.resolve(2)))
Promise.resolve().then(() => {
  throw new Error('error')
}); // 返回值 new Promise(resolve => resolve(Promise.reject(new Error('error'))))
Promise.reject().then(() => 1, () => 2); // 返回值为 new Promise(resolve => resolve(2))

// catch
Promise.reject().catch(() => 3); // 返回值为 new Promise(resolve => resolve(3))
Promise.resolve().catch(() => 4); // 返回值为 new Promise(resolve => resolve(调用catch的promise))

// finally
Promise.resolve().finally(() => {})
Promise.reject().finally(() => {})
// 返回值都为 new Promise(resolve => resolve(调用finally的promise对象))

```
